# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gofibsvc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gofibsvc
  template:
    metadata:
      labels:
        name: gofibsvc
    spec:
      containers:
      - name: gofibsvc
        image: noelruault/go-fibonacci:latest
        imagePullPolicy: IfNotPresent # Points to local and remote docker registry
        ports:
          - containerPort: 8080

---

# Service
apiVersion: v1
kind: Service
metadata:
  name: gofibsvc-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    name: gofibsvc
